<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Lmp.Application\Lmp.Application.csproj" />
    <ProjectReference Include="..\Lmp.Domain\Lmp.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Auth\data\disposable_email_blocklist.conf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
