package com.lmp.support.domain;

public enum AuditEventType {
    SESSION_CREATED,
    SESSION_INVITED,
    CONSENT_GIVEN,
    CONSENT_REFUSED,
    CONSENT_TIMEOUT,
    SESSION_STARTED,
    SESSION_DEGRADED,
    SESSION_ENDED,
    SESSION_ABORTED,
    RECORDING_AVAILABLE,
    COMMAND_EXEC,
    COMMAND_BLOCKED,
    AI_SUGGESTED,
    AI_APPROVED,
    AI_REJECTED,
    AI_INJECTION_ATTEMPT,
    AI_HALLUCINATION_SUSPECTED
}
