# Configuration du serveur
server.port=8080

# Configuration Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Configuration des ressources statiques
spring.web.resources.static-locations=classpath:/static/

# Configuration de développement
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Logging pour le développement
logging.level.com.lmp=DEBUG
logging.level.org.springframework.web=DEBUG
