server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Compression GZIP pour améliorer les performances
    gzip on;
    gzip_vary on;
    gzip_min_length 10240;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml application/javascript;

    # Gérer le routage d'Angular (redirection vers index.html)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Configuration du cache pour les fichiers statiques (images, css, js)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }

    # Interdire l'accès aux fichiers cachés
    location ~ /\. {
        deny all;
    }
}
